Add unique identifiers for iCal exports, to allow Google Calendar imports without User Auth
letsmeet-click/letsmeet.click pull request #57
Opened 2017-01-24 22:39 UTC by NotANormalNerd

Implements #56

2017-01-25 13:25 UTC, michael-k requested changes

2017-01-25 13:25 UTC, michael-k commented on letsmeet/events/feeds.py
> +class ICalPersonalUserEventsFeed(ICalCommunityEventsFeed):
DRY:
```python
class ICalPersonalUserEventsFeed(ICalUserEventsFeed):
```

2017-01-25 13:25 UTC, michael-k commented on letsmeet/events/urls.py
> +from .feeds import LatestEventsFeed, ICalCommunityEventsFeed, ICalUserEventsFeed, ICalPersonalUserEventsFeed
this line is getting to long

2017-01-25 13:25 UTC, michael-k commented on letsmeet/users/templates/users/dashboard.html
> +          <a class="btn btn-default" href="{% url 'personal_events_ical_feed_uuid' uuid=userprofile.personal_ical_uuid %}"><i class="fa fa-calendar"></i> ical calendar (Google importable)</a>
indentation matters

2017-01-25 13:59 UTC, asmaps commented
I think it would also be okay to replace the current feed.

2017-01-30 13:10 UTC, NotANormalNerd commented
@michael-k Thank you for the review. I will change the stuff mentioned and come back.
@asmaps Yes it is probabl a good idea. I will remove the current feed and replace it with my implementation.
I will do the changes as soon as I have time.

2017-02-03 15:45 UTC, asmaps commented
Will review and merge as soon as I have time.
Anymore comments @michael-k ?

2017-02-06 07:32 UTC, michael-k commented on letsmeet/communities/models.py
>      default = models.Manager()   # the default manager
This is due to a bug in pycodestyle.  Should not be changed in this PR.
See issue 617 of https://github.com/PyCQA/pycodestyle

2017-02-06 07:32 UTC, michael-k commented on letsmeet/users/templates/users/dashboard.html
> +          </div>
Indentation is broken, but it was broken before (just in a different way ;) ).
Maybe change it to 4 spaces (to be consistent with the rest of the file).

2017-02-23 22:52 UTC, michael-k approved these changes
LGTM

2017-03-03 23:24 UTC, michael-k commented
ping @asmaps @mfa

2017-03-07 18:37 UTC, merged